name: CI for SSH with Custom Domain (Cloudflare DNS)

on: [push, workflow_dispatch]

jobs:
  setup-linux:
    runs-on: ubuntu-latest
    steps:
    
    - name: Update and Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip openssh-server wget

    - name: Enable SSH
      run: |
        sudo systemctl enable ssh
        sudo systemctl start ssh
    
    - name: Set Up User for SSH Access
      run: |
        sudo useradd -m -s /bin/bash adminn
        echo "adminn:Admin@123" | sudo chpasswd
        echo "adminn ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/adminn
    
    - name: Configure Firewall for SSH
      run: |
        sudo ufw allow OpenSSH
        sudo ufw enable

    - name: Get Public IP Address of the Instance
      run: |
        PUBLIC_IP=$(curl -s ifconfig.me)
        echo "Public IP for SSH: $PUBLIC_IP"
    
    - name: Configure Cloudflare DNS for Custom Domain
      run: |
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
        sudo dpkg -i cloudflared.deb && 
        sudo cloudflared service install ${{secrets.C_TOKEN}} 
    - name: Display SSH Command
      run: |
        echo "SSH Connection Command: ssh adminn@"
